print('='*40)
nome = input('Olá Jovem Gafanhoto. \nQual é o seu nome? ').capitalize().strip()
print('\033[1;42mOlá {}!\033[m'.format(nome))
print('Aqui iniciamos nossos projetos !\nVamos estudar Python AGORA')
print('='*40)